# -*- coding: utf-8 -*-
"""ANALISIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IVq9h_wY2reEiwCRvtqUU179zWPdGfp7
"""

import pandas as pd 
import numpy as np
import calendar
from datetime import datetime, timedelta
import statistics as stat
import matplotlib.pyplot as plt

data = pd.read_excel('/content/VENTAS.xlsx')

"""# ***ANALISIS DE LOS DATOS***



"""

data.head()

data.head()

print(data.shape)
print(data.dtypes)

data.isnull().sum()

"""# **LIMPIEZA DE DATOS**

"""

data= data.drop(['PRODUCTO2', 'PRODUCTO3', 'PRODUCTO4', 'PRODUCTO5', 'PRODUCTO6', 'PRODUCTO7', 'Columna18'], axis=1)

data['COSTOTOTAL'] = data['COSTOTOTAL'].str.replace('.00', '0')
data['COSTOTOTAL'] = data['COSTOTOTAL'].str.replace(',', '')

data.COSTOTOTAL = data.COSTOTOTAL.astype(float)

def depurar(datos):
  for i in range(0,len(datos.columns)):
    atributo = datos.columns[i]
    if (datos.isnull()[atributo].sum() != 0): #si hay valores nulos en la columna
      datos[atributo].fillna(0,inplace=True) #llena con nas
depurar(data)

for i in range(0, len(data)):
  if pd.isnull(data['ESTADO'][i]):
    data['ESTADO'][i] = 'Leído'

for i in range(0, len(data)):
  if pd.isnull(data['CORREO'][i]):
    data['CORREO'][i] = 'Sin Especificar'

for i in range(0, len(data)):
  if pd.isnull(data['TELEFONO'][i]):
    data['TELEFONO'][i] = 'Sin Especificar'

"""# **ANALISIS ESTADISTICO**"""

min_date = data.FECHA.min()
max_date = data.FECHA.max()
print(min_date, max_date)

date_start="%s-0%s" % (min_date.year, min_date.month)
date_end="%s-0%s" % (max_date.year, max_date.month)
date_start=np.datetime64(date_start)
date_end=np.datetime64(date_end)
array_fechas = np.arange(date_start, date_end+1)

means=[]
for fecha_idx in range(len(array_fechas)-1):
  means+=[np.sum([int(x) for x in data.COSTOTOTAL.loc[(data.FECHA>array_fechas[fecha_idx]) & (data.FECHA<array_fechas[fecha_idx+1])]])]
print("En el mes se espera una venta de: ",int(np.mean(means)), 'COP')

ceds=sorted(set(list(data['CEDULA'])),key=list(data['CEDULA']).count, reverse=True)
numero_clientes=5
print("Los clientes con mayor probabilidad de volver a comprar son: ")
for i in range(numero_clientes):
  name=data['NOMBRE'][data['CEDULA']==ceds[i]]
  avg_cost=np.mean([int(x) for x in data.COSTOTOTAL.loc[data['CEDULA']==ceds[i]]])
  print(name.values[0], 'promedio de compra: ', int(avg_cost))

