# -*- coding: utf-8 -*-
"""ANALISIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IVq9h_wY2reEiwCRvtqUU179zWPdGfp7
"""

import pandas as pd #manejo y analisis de estructuras de datos
import numpy as np #cclculo numerico y analisis de datos
from datetime import datetime, timedelta #manejo de fechas
import missingno as msno #manejo de valores faltantes

data = pd.read_excel('/content/VENTAS.xlsx') #se asigna la BD a una variable

"""# ***ANALISIS DE LOS DATOS***



"""

data.head() #Visualizar los primeros registros de la BD

print(data.shape) #Conocer las dimensiones de la BD
print(data.dtypes) #Conocer los tipos de datos que tienen las columnas

msno.matrix(data) #Grafico de nulos por columna

data.isnull().sum() #Sumar los nulos por columna que hay en los registros

data.describe(include='O') #Da una descripcion general de los registros

data['PRODUCTO'].unique() #Para mirar los valores que hay en una columna

data['ESTADO'].unique()

"""# **LIMPIEZA DE DATOS**

"""

data['PRODUCTO']=data['PRODUCTO'].str.lower() #Se convierten todos los registros a minuscula
data['NOMBRE']=data['NOMBRE'].str.lower()

data= data.drop(['Columna18'], axis=1) #Se borran columnas que no dan información util

#Se hace un reemplazo de ciertas caracteristicas para poder manipular los datos más adelante
data['COSTOTOTAL'] = data['COSTOTOTAL'].str.replace('.00', '0')
data['COSTOTOTAL'] = data['COSTOTOTAL'].str.replace(',', '')

data.COSTOTOTAL = data.COSTOTOTAL.astype(float) #Se cambia el tipo de dato

mean_c=data['COSTOTOTAL'].mean() #Para sacar en una variable a aparte la media de costototal
print(mean_c)

"""PARA RELLENAR NULOS Y OTROS

"""

for i in range(0, len(data)):
  if ((data['ESTADO'][i] == 'Enviado') & (data['COSTOTOTAL'][i] == 0)):
    data['COSTOTOTAL'][i]= mean_c

for i in range(0, len(data)):
  if ((data['ESTADO'][i]) == 'Leída')  | pd.isnull(data['ESTADO'][i]):
    data['ESTADO'][i] = 'Leído'

for i in range(0, len(data)):
  if pd.isnull(data['CORREO'][i]):
    data['CORREO'][i] = 'Sin Especificar'

for i in range(0, len(data)):
  if pd.isnull(data['TELEFONO'][i]):
    data['TELEFONO'][i] = 'Sin Especificar'

for i in range(0, len(data)):
  if pd.isnull(data['PRODUCTO'][i]):
    data['PRODUCTO'][i] = 'Sin Especificar'

def depurar(datos):
  for i in range(0,len(datos.columns)):
    atributo = datos.columns[i]
    if (datos.isnull()[atributo].sum() != 0): #Si hay valores nulos en la columna
      datos[atributo].fillna(0,inplace=True) #Llena con 0
depurar(data)

"""# **ANALISIS ESTADISTICO**"""

#Funciones para sacar la fecha max y min
min_date = data.FECHA.min()
max_date = data.FECHA.max()
print(min_date, max_date)

#Se guardan las fechas en una variable y se convierte en datetime para guardarlas en un array
date_start="%s-0%s" % (min_date.year, min_date.month)
date_end="%s-0%s" % (max_date.year, max_date.month)
date_start=np.datetime64(date_start)
date_end=np.datetime64(date_end)
array_fechas = np.arange(date_start, date_end+1)

means=[]
for fecha_idx in range(len(array_fechas)-1):
  means+=[np.sum([int(x) for x in data.COSTOTOTAL.loc[(data.FECHA>array_fechas[fecha_idx]) & (data.FECHA<array_fechas[fecha_idx+1])]])]
print("En el mes se espera una venta de: ",int(np.mean(means)), 'COP')

ceds=sorted(set(list(data['CEDULA'])),key=list(data['CEDULA']).count, reverse=True)
numero_clientes=5
print("Los clientes con mayor probabilidad de volver a comprar son: ")
for i in range(numero_clientes):
  name=data['NOMBRE'][data['CEDULA']==ceds[i]]
  avg_cost=np.mean([int(x) for x in data.COSTOTOTAL.loc[data['CEDULA']==ceds[i]]])
  print(name.values[0], 'promedio de compra: ', int(avg_cost))
